### ISSUE TITLE
date type should be date instead of long

### ISSUE THREAD

**Issue by whollacsek** [ozlerhakan/mongolastic#19]
I'm trying to use data imported by mongolastic with kibana and I just found out the type mapping for date type is wrong. According to https://github.com/elastic/kibana/issues/3347 it should be date, not long.

Is it possible to configure it in the config file?

**Comment by ozlerhakan** [comment]
Hi @whollacsek ,

I would like to help you to make this feature available but first I need sample data to investigate it. Could you share example documents with me? I have not used Kibana. which steps should I follow to get what you really say?

**Comment by whollacsek** [comment]
Hi @ozlerhakan here are some steps to explain what I meant:
1. Create a mongo database with some data

``` shell
mongo --eval '
db.events.insert(
[{
    "createdAt" : ISODate("2016-06-03T16:25:39.542Z"),
    "timestamp" : ISODate("2016-06-03T16:25:03.773Z"),
    "value" : "1"
},{
    "createdAt" : ISODate("2016-06-04T16:25:39.542Z"),
    "timestamp" : ISODate("2016-06-04T16:25:03.773Z"),
    "value" : "2"
},{
    "createdAt" : ISODate("2016-06-05T16:25:39.542Z"),
    "timestamp" : ISODate("2016-06-05T16:25:03.773Z"),
    "value" : "3"
}]
)' mongolastic19
```
1. Prepare config.yaml

``` yml
misc:
   dindex:
       name: mongolastic19
       as: mongolastic19
   ctype:
       name: events
       as: event
   batch: 200
   dropDataset: true
mongo:
   host: localhost
   port: 27017
elastic:
   host: localhost
   port: 9300
```
1. Run `java -jar mongolastic.jar -f config.yaml`
2. Inspect elasticsearch index

```
curl -XGET http://localhost:9200/mongolastic19
```

Result:

```
{
    "mongolastic19": {
        "aliases": {},
        "mappings": {
            "event": {
                "properties": {
                    "createdAt": {
                        "properties": {
                            "$date": {
                                "type": "long"
                            }
                        }
                    },
                    "timestamp": {
                        "properties": {
                            "$date": {
                                "type": "long"
                            }
                        }
                    },
                    "value": {
                        "type": "string"
                    }
                }
            }
        },
        "settings": {
            "index": {
                "creation_date": "1477584818718",
                "number_of_shards": "5",
                "number_of_replicas": "1",
                "uuid": "6ft-7IIUSziWrYBzibmOog",
                "version": {
                    "created": "2030399"
                }
            }
        },
        "warmers": {}
    }
}
```

---

So we got :

```
"timestamp": {
    "properties": {
        "$date": {
            "type": "long"
        }
    }
}
```

Instead of (maybe):

```
"timestamp": {
    "properties": {
        "$date": {
            "type": "date"
        }
    }
}
```

Basically Kibana needs a field of type date to do compute charts, but I do not know if the type date should be specified like above.

**Comment by ozlerhakan** [comment]
Ah I see, you can use  **`dateFormat: "<format>'`** with mongolastic.

You can give any format that [elasticsearch supports](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping-date-format.html#built-in-date-formats). 

For example;

config.yaml

```
misc:
   dindex:
       name: mongolastic19
       as: mongolastic19
   ctype:
       name: events
       as: event
   batch: 200
   dropDataset: true
mongo:
   host: localhost
   port: 27017
elastic:
   host: localhost
   port: 9300
   dateFormat: "yyyy-MM-dd"
```

After running mongolastic, you should see the mapping of the newly created index as follows:

```
{
    "mongolastic19": {
        "mappings": {
            "event": {
                "properties": {
                    "createdAt": {
                        "format": "strict_date_optional_time||epoch_millis",
                        "type": "date"
                    },
                    "timestamp": {
                        "format": "strict_date_optional_time||epoch_millis",
                        "type": "date"
                    },
                    "value": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
```
