### ISSUE TITLE
Distant connection

### ISSUE THREAD

**Issue by thehomer** [ozlerhakan/mongolastic#7]
Hi !

I tried to use your plugin on ubuntu 14.04 with elasticsearch 2.3.1.
Everywhere i find the syntaxe for a localhost mongodb, but what is the syntax for a distant mongodb with authentication and connection on admin db ?

I always have this message when I launch : java -jar mongolastic.jar -f config_mongo.file

5837 [main] INFO org.elasticsearch.client.transport  - [MODOK] failed to get node info for {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9200}, disconnecting...

my elasticsearch is running, verify with : curl -X GET 'http://localhost:9200'

{
  "name" : "Alex Hayden",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
....
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

Thank you !

**Comment by ozlerhakan** [comment]
Hi @thehomer ,

> Everywhere i find the syntaxe for a localhost mongodb, but what is the syntax for a distant mongodb with authentication and connection on admin db ?

The current mongolastic tool does not support authentication to connect an auth mongod. This will be the next future request, we need to implement it.

If you look at the log of an elasticsearch node, you should see two different port numbers one for http, one for transport:

```
$ elasticsearch
....
[INFO ][http] [Mosha] publish_address {127.0.0.1:9200},bound_addresses {127.0.0.1:9200}, {[::1]:9200}
[INFO ][transport] [Mosha] publish_address {127.0.0.1:9300},bound_addresses {127.0.0.1:9300}, {[::1]:9300}
.....
```

You need to specify the number of transport, in this example, 9300 is the key. If It is possible could you try to connect an unauthenticated mongod server and elasticsearch node. i.e.:

```
[....]
[....]
mongo:
    host: <ip-address>
    port: <port-number>
elastic:
    host: <ip-address> 
    port: 9300 
```

### Future Request

For the future request, we need to give an option to users to write an username, password and authenticationDatabase name in order to connect to an auth MongoDB. At first glance, I have thought of something like this:

```
[....]
[....]
mongo:
    host: <ip-address>
    port: 27017
    user: hakan
    pwd: 123
    authenticationDatabase: admin
elastic:
    host: <ip-address> 
    port: 9300 
```
